import type { Metadata } from "next";
import "./globals.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import { ReduxProvider } from "./lip/stroeProvider";
import Navbar from "./components/Navbar";



export const metadata: Metadata = {
  title: "Bebek Baby",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <Navbar/>
        {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
